apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qwo3gchtr-go 
  janus-idp.io/tekton: qwo3gchtr-go
  backstage.io/kubernetes-id: qwo3gchtr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qwo3gchtr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  