apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qwo3gchtr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qwo3gchtr-go 
  name: qwo3gchtr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qwo3gchtr-go 
